fix: if job fails

diff --git a/.azure-pipelines/templates/aml-job-create/step.yaml b/.azure-pipelines/templates/aml-job-create/step.yaml
--- a/.azure-pipelines/templates/aml-job-create/step.yaml
+++ b/.azure-pipelines/templates/aml-job-create/step.yaml
@@ -44,6 +44,11 @@ steps:
               sleep 60s
               echo "##[debug]Still queued/running" 
             done
+
+            if [[ $(az ml job show -n $JOB_NAME --resource-group ${{ parameters.resourceGroup }} --workspace-name ${{ parameters.workspaceName }} | jq -r '.status') == "Failed" ]];
+              echo "##vso[task.logissue type=error;]Remote job status is failed."
+              exit 1
+            fi
           fi
         fi
     target:
diff --git a/.github/actions/aml-job-create/action.yaml b/.github/actions/aml-job-create/action.yaml
--- a/.github/actions/aml-job-create/action.yaml
+++ b/.github/actions/aml-job-create/action.yaml
@@ -62,6 +62,11 @@ runs:
               sleep 60s
               echo "::debug::Still queued/running" 
             done
+
+            if [[ $(az ml job show -n $JOB_NAME --resource-group ${{ inputs.resourceGroup }} --workspace-name ${{ inputs.workspaceName }} | jq -r '.status') == "Failed" ]];
+              echo "::error::Remote job status is failed."
+              exit 1
+            fi
           fi
         fi
 
