fix: job submit error message

diff --git a/.azure-pipelines/templates/aml-job-create/step.yaml b/.azure-pipelines/templates/aml-job-create/step.yaml
--- a/.azure-pipelines/templates/aml-job-create/step.yaml
+++ b/.azure-pipelines/templates/aml-job-create/step.yaml
@@ -51,15 +51,15 @@ steps:
             echo "##vso[task.logissue type=warning;]Log capturing didn't work. Check experiment details."
             echo "##[debug]Waiting for the job "
             JOB_STATUS="Queued"
-            while [[ $JOB_STATUS =~ ^(Running|Queued|Preparing)$ ]];
+            while ! [[ $JOB_STATUS =~ ^(Failed|Completed|Canceled)$ ]];
             do
               sleep 60s
               echo "##[debug]Still queued/running"
               JOB_STATUS=$(az ml job show -n $JOB_NAME --resource-group ${{ parameters.resourceGroup }} --workspace-name ${{ parameters.workspaceName }} | jq -r '.status')
             done
 
-            if [[ $JOB_STATUS == "Failed" ]]; then
-              echo "##vso[task.logissue type=error;]Remote job status is failed."
+            if [[ $JOB_STATUS != "Completed" ]]; then
+              echo "##vso[task.logissue type=error;]Remote job status is failed or canceled."
               exit 1
             fi
           fi
