fix: cliv2 for models

diff --git a/.azure-pipelines/templates/aml-model-register/step.yaml b/.azure-pipelines/templates/aml-model-register/step.yaml
--- a/.azure-pipelines/templates/aml-model-register/step.yaml
+++ b/.azure-pipelines/templates/aml-model-register/step.yaml
@@ -9,14 +9,14 @@ parameters:
 - name: fromJob
   type: boolean
   default: false
+- name: fromAnotherWorkspace
+  type: boolean
+  default: false
 - name: jobName
   type: string
   default: .
 - name: modelPath
   type: string
-- name: modelVersion
-  type: string
-  default: 
 - name: workspaceName
   type: string
   default: 
@@ -26,22 +26,30 @@ parameters:
 
 steps:
   - task: AzureCLI@2
-    name: modelRegistration
     displayName: Registering model
     inputs:
       scriptType: bash
       scriptLocation: inlineScript
       azureSubscription: ${{ parameters.azureServiceConnectionName }}
       inlineScript: |
-        SUBSCRIPTION_ID=$(az account show | jq -r ".id")
-        echo "##[debug]Working on subscription $SUBSCRIPTION_ID"
-        
-        python -m jobtools $(Build.SourcesDirectory)/.azure-pipelines/templates/aml-model-register/register.py register \
-          --subscription-id $SUBSCRIPTION_ID \
-          --workspace-name ${{ parameters.workspaceName }} \
-          --resource-group ${{ parameters.resourceGroup }} \
-          --name ${{ parameters.name }} \
-          --version ${{ parameters.modelVersion }} \
-          --model-path ${{ parameters.modelPath }} \
-          --description "${{ parameters.description }}" \
-          --run-id ${{ parameters.jobName }}
+        if ${{ lower(parameters.fromJob) }}; then
+          if ${{ lower(parameters.fromAnotherWorkspace) }}; then
+            echo "##[debug]Downloading assets from job ${{ parameters.jobName }}"
+            az ml job download --name ${{ parameters.jobName }} --resource-group ${{ parameters.resourceGroup }} --workspace-name ${{ parameters.workspaceName }}
+            echo "##[debug]$(ls)"
+
+            MODEL_PATH="${{ parameters.jobName }}/${{ parameters.modelPath }}"
+          else
+            MODEL_PATH="azureml://jobs/${{ parameters.jobName }}/outputs/artifacts/${{ parameters.modelPath }}"
+          fi
+        else
+          if test -f "${{ parameters.jobName }}/${{ parameters.modelPath }}"; then
+            echo "##vso[task.logissue type=error]File ${{ parameters.modelPath }} not found."
+            exit 1
+          fi
+
+          MODEL_PATH="${{ parameters.modelPath }}"
+        fi
+
+        echo "##[debug]Creating model from path $MODEL_PATH"
+        az ml model create --name ${{ parameters.name }} --description ${{ parameters.description }} --path $MODEL_PATH --resource-group ${{ parameters.resourceGroup }} --workspace-name ${{ parameters.workspaceName }}
